export const INIT_DEFAULT_LOCATION = 'INIT_DEFAULT_LOCATION';
export const INIT_LOCATION = 'INIT_LOCATION';
export const INIT_LOCATION_DETAILS = 'INIT_LOCATION_DETAILS';

export const INIT_LOCATIONS_LIST = 'INIT_LOCATIONS_LIST';

export const ADD_LOCATION_FAV_LIST = 'ADD_LOCATION_FAV_LIST';
export const REMOVE_LOCATION_FAV_LIST = 'REMOVE_LOCATION_FAV_LIST';

export const SET_DEFAULT_LOCATION_CITY = 'SET_DEFAULT_LOCATION_CITY';